research_channel:
  description: >
    Conduct a thorough research about {topic}
    Make sure to find interesting and relevant information given
    the current year is 2024.
  expected_output: >
    A list with 5 top youtube channel handles of the most relevant information about {topic}
  agent: channel_researcher


analyze_channel:
  description: >
    Analyze the content of a youtube channel and provide a detailed report of the key learning points of a youtube channel's coverage on the {topic}
  expected_output: >
    A detailed report of the key learning points of a youtube channel's coverage on the {topic}
  agent: channel_analyzer


create_quiz:
  description: >
    Create an engaging and informative quiz to test the knowledge of the user and teach him the important key points on {topic}
  expected_output: >
    An engaging and informative quiz to test the knowledge of the user and teach him the important key points on {topic}.
    10 questions with multiple choice answers with the correct answer highlighted.
  agent: quiz_maker